#	Makefile for unit Hydro/HydroMain/Spark/UniformMeshNewImpl
# The mesh core + the pre-expanded NewImpl sources are placed in this directory by
# ~/UniformMesh/flashx/install_newimpl.sh; they compile as part of the Hydro unit.
Hydro += mesh.o mesh_bind.o mesh_f.o um_flashx.o hydro_grid_contract.o \
         hy_getFaceFlux.o hy_updateSolution.o hy_shockDetect.o hy_computeDt.o \
         hy_prepareAdvance.o uniformmesh_grid.o
